[versions]
agp = "8.1.2"
kotlin = "1.9.10"

[kotlin]
stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin}"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"

[plugin]
AGP = "com.android.tools.build:gradle:${agp}"
KGP = "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin}"

[androidx]
appcompat = "androidx.appcompat:appcompat:1.6.1"
coreKtx = "androidx.core:core-ktx:1.12.0"
fragmentKtx = "androidx.fragment:fragment-ktx:1.6.1"
