[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21"

[lib]
name = "rust"
crate_type = ["staticlib", "dylib"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
