name: Android CI

on:
  push:
  repository_dispatch:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk

      - name: Cache Kotlin Native dependencies
        uses: actions/cache@v4
        with:
          path: ~/.konan/cache
          key: ${{ runner.os }}-kotlin-native-${{ hashFiles('**/*.kts') }}
          restore-keys: ${{ runner.os }}-kotlin-native-

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@main
        with:
          toolchain: stable
          target: armv7-linux-androideabi i686-linux-android aarch64-linux-android x86_64-linux-android

      - name: Add Android targets
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Upload to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/release/*.apk
          asset_name: JPSyllabary
          tag: ${{ github.ref }}_${{ steps.time.outputs.time }}
          overwrite: true
          file_glob: true

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 2
